spring:
  application:
    name: dear-comrade-spring-zero-to-hero
  profiles:
    group:
      dev:
        - "dear"
        - "helper-dev"
      local:
        - "helper-local"
app:
  profile: default

ott:
  enabled: true